OnlineMarketPlace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include('items.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversation/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('new/<int:item_pk>/', views.new_conversation, name="new"),
    path('<int:pk>/', views.detail, name='detail'),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name="contact"),
    path('signUp/', views.signUp, name="signUp"),
    path('user_login/', views.user_login, name="user_login"),
    path('logout_user/', views.logout_user, name="logout_user"),
]

items/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'items'

urlpatterns = [
    path('', views.itemsSearch, name="itemsSearch"),
    path('<int:pk>/',views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('<int:pk>/delete/', views.delete, name="delete"),
    path('<int:pk>/edit/', views.edit, name="edit"),
]

items/models.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name

items/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'form-control py-2 rounded-3 border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image',)
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': 'form-control py-0 px-0 rounded-3 border-0'
            })
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

items/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Item
from django.contrib.auth.decorators import login_required
from .forms import NewItemForm, EditItemForm

from django.db.models import Q


# Create your views here.

def itemsSearch(request):
    query = request.GET.get('query','')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(category_id=category_id)
    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'item/items.html', { 'items': items, 'query': query, 'categories': categories,'category_id': int(category_id)})

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]
    return render (request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })


@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('items:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {'form': form, 'title': 'New Item'})

@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()

            return redirect('items:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)
    
    return render(request, 'item/form.html', {'form':form, 'title':'Edit Item'})

items/templates/item/detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
<h2>This is a Details Page</h2>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <img src="{{ item.image.url }}" class="img-thumbnail" style="height: 300px;">
        </div>
        <div class="col-md-8">
            <h1 class="mb-5" style="text-transform: uppercase;">{{item.name}}</h1>
            <p class="" style="color:rgb(126, 133, 133);"><strong>Price: </strong>{{ item.price }}</p>
            <p style="color:rgb(126, 133, 133);"><strong>Seller: </strong>{{ item.created_by.username }}</p>

            {% if item.description %}
                <p class="text-gray-700">
                    <strong class="text-gray-500">Description:</strong><br>
                    {{ item.description }}
                </p>
            {% endif %}

            {% if request.user == item.created_by %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>This is your item!</p>

                <a href="{% url 'items:edit' item.id %}" class="btn btn-primary">Edit</a>
                <a href="{% url 'items:delete' item.id %}" class="btn btn-danger">Delete</a>
            </div>
            {% else %}  
                <a href="{% url 'conversation:new' item.id %}" class="d-inline-block mt-3 px-4 py-2 fs-5 fw-semibold bg-primary text-white rounded-3 hover:bg-primary-dark">Contact seller</a>
            {% endif %}
        </div>
    </div>

    <div class="row mb-5 mt-5">
        <h2 class="text-center">Related items</h2>

        {% for item in related_items %}
        <div class="col-md-4">
            <a href="{% url 'items:detail' item.id %}" style="text-decoration: none; color: black;">
            <div class="card">
                <img class="card-img-top" src="{{item.image.url}}" alt="Card image cap" style="height:210px">
                <div class="card-body">
                  <h5 class="card-title itemTitle" style="text-decoration: none; text-transform: capitalize; color: black;">{{item.name}}</h5>
                  <p class="card-text">{{item.description|truncatechars:20}}</p>
                </div>
                <div class="card-footer">
                  <div class="row">
                    <div class="col-md-10">
                        <p style="font-weight: 600;">Price: ${{item.price}}</p>
                    </div>
                    <div class="col-md-2">
                        
                    </div>
                  </div>
                </div>
            </div>
            </a>
        </div>
        {% endfor %}
    </div>

</div>



{% endblock content %}

items/templates/item/form.html
{% extends 'core/base.html' %}

{% block content %}
<h1 class="mb-4 fs-4 text-center">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3 col-md-6 mx-auto">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-danger text-white rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <div style="display: flex; justify-content: center; align-items: center; margin-bottom: 20px; width: 100%;">
        <button type="submit" class="btn btn-primary mt-4" style="width: 50%;">Submit</button>
    </div>
</form>
{% endblock %}

items/templates/item/items.html
{% extends 'core/base.html' %}

{% block content %}
<div class="pb-6 row g-4 bg-gray-100">
    <div class="col-md-3">
        <form method="get" action="{% url 'items:itemsSearch' %}">
            <input name="query" class="w-100 py-2 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find a bike, a chair or car...">

            <button class="mt-3 btn btn-secondary">Search</button>
        </form>

        <hr class="my-6">

        <p class="font-weight-bold">Categories</p>

        <ul class="list-unstyled">
            {% for category in categories %}
                <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-light {% endif %}" style="color:black;">
                    <a class="categoryName" href="{% url 'items:itemsSearch' %}?query={{ query }}&category={{ category.id }}" style="text-decoration: none; color: black; font-weight: 400; font-size: 20px;">{{ category.name }}</a>
                </li>
            {% endfor %}
        </ul>

        <hr class="my-6">

        <p class="font-weight-bold">Clear filters</p>

        <ul class="list-unstyled">
            <li><a href="{% url 'items:itemsSearch' %}" class="btn btn-outline-warning btn-lg">Clear</a></li>
        </ul>
    </div>

    <div class="col-md-9">
        <div class="row row-cols-3 g-4">
            {% for item in items %}
                <div class="col-md-4 mb-4">
                    <a href="{% url 'items:detail' item.id %}" style="text-decoration: none; color: black;">
                    <div class="card">
                        <img class="card-img-top" src="{{item.image.url}}" alt="Card image cap" style="height:210px">
                        <div class="card-body">
                        <h5 class="card-title itemTitle" style="text-decoration: none; text-transform: capitalize; color: black;">{{item.name}}</h5>
                        <p class="card-text">{{item.description|truncatechars:20}}</p>
                        </div>
                        <div class="card-footer">
                        <div class="row">
                            <div class="col-md-10">
                                <p style="font-weight: 600;">Price: ${{item.price}}</p>
                            </div>
                            <div class="col-md-2">
                                
                            </div>
                        </div>
                        </div>
                    </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock content %}