OnlineMarketPlace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include('items.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversation/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('new/<int:item_pk>/', views.new_conversation, name="new"),
    path('<int:pk>/', views.detail, name='detail'),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name="contact"),
    path('signUp/', views.signUp, name="signUp"),
    path('user_login/', views.user_login, name="user_login"),
    path('logout_user/', views.logout_user, name="logout_user"),
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('',views.index, name="index")
]

items/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'items'

urlpatterns = [
    path('', views.itemsSearch, name="itemsSearch"),
    path('<int:pk>/',views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('<int:pk>/delete/', views.delete, name="delete"),
    path('<int:pk>/edit/', views.edit, name="edit"),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Your username','class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Your password','class': 'form-control'}))
    
class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'form-control'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'form-control'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'form-control'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'form-control'
    }))

core/views.py
from django.shortcuts import render, redirect
from items.models import Category, Item
from .forms import SignupForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


# Create your views here.

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all() 
    return render(request, 'core/index.html', {'items':items, 'categories':categories})

def contact(request):
    return render(request, "core/contact.html")


def signUp(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "You have successfully register! Welcome!")
            return redirect('/user_login/')
    else:
        form = SignupForm()
    return render(request, 'core/signup.html', {'form':form})

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        # Authenticate
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "You Have Been Logged in!")
            return redirect("index")
        else:
            messages.success(request, "There is a problem for login . Please Try again. ")
            return redirect("index")
    else:
        return render(request, 'core/login.html');

def logout_user(request):
    logout(request)
    messages.success(request, "You have been logged out")
    return redirect("user_login")

core/templates/core/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Online MarketPlace</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body>
    {% include 'core/navbar.html' %}
    <div class="container">
      <br/>
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>


        {% endfor %}
      {% endif %}
      
      <div class="px-6 py-6">
        {% block content %}

        {% endblock%}
      </div>
 
    </div>

    <!-- {% include 'core/footer.html' %} -->
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

<!-- {% block title %}Contact{% endblock %} -->

{% block content %}
    <h1 class="text-center">The contact page</h1>
    <div class="form-area mb-5">
        <div class="container">
            <div class="row single-form g-0">
                <div class="col-sm-12 col-lg-6">
                    <div class="left">
                        <h2><span>Contact Us For</span> <br>Business Enquiries</h2>
                    </div>
                </div>
                <div class="col-sm-12 col-lg-6">
                    <div class="right">
                        <i class="fa fa-caret-left"></i>
                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="mb-3">
                              <label for="exampleInputEmail1" class="form-label">Your Name</label>
                              <input type="text" class="form-control" id="exampleInputtext" aria-describedby="emailHelp">
                            </div>
                            <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label">Your Email</label>
                                <input type="email" class="form-control" id="exampleInputtext" aria-describedby="emailHelp">
                            </div>
                            <div class="mb-3">
                                <label for="exampleInputPassword1" class="form-label">Message</label>
                                <textarea class="form-control"></textarea>
                            </div>                            
                            
                            <button type="submit" class="btn btn-primary">Submit</button>
                          </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/footer.html
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-sm-6">

            </div>
        </div>
    </div>
</footer>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row mb-5">
        <h2 class="text-center">Newest items</h2>

        {% for item in items %}
        <div class="col-md-4 mb-4">
            <a href="{% url 'items:detail' item.id %}" style="text-decoration: none; color: black;">
            <div class="card">
                <img class="card-img-top" src="{{item.image.url}}" alt="Card image cap" style="height:210px">
                <div class="card-body">
                  <h5 class="card-title itemTitle" style="text-decoration: none; text-transform: capitalize; color: black;">{{item.name}}</h5>
                  <p class="card-text">{{item.description|truncatechars:20}}</p>
                </div>
                <div class="card-footer">
                  <div class="row">
                    <div class="col-md-10">
                        <p style="font-weight: 600;">Price: ${{item.price}}</p>
                    </div>
                    <div class="col-md-2">
                        
                    </div>
                  </div>
                </div>
            </div>
            </a>
        </div>
        {% endfor %}
    </div>

    <div class="row mb-5">
        <h2 class="text-center">Categories</h2>

        {% for category in categories %}
        <div class="col-md-4">
            <a href="#" style="text-decoration: none; color: black;">
            <div class="card" style="margin-bottom: 20px; border: 1px solid rgb(226, 224, 220);">
                <div class="bg-light rounded-b-xl" style="padding: 20px;">
                    <h2 class="text-xl">{{ category.name }}</h2>
                    <p class="text-gray-500">{{ category.items.count }} items</p>
                </div>
            </div>
            </a>
        </div>
        {% endfor %}
    </div>
  </div>
  
{% endblock content %}

core/templates/core/login.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}

<div class="col-md-6 offset-md-3">
    <h1 class="text-center">Login</h1>
    <br/>
    
    <form method="POST" action="#" class="border rounded p-3" style="max-width: 400px; margin: 0 auto;">
        {% csrf_token %}
    
      <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" class="form-control" name="username" id="username" placeholder="Enter your username" required>
      </div>
      <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" name="password" id="password" placeholder="Enter your password" required>
      </div>
      <button type="submit" class="btn btn-primary">Login</button>
      
    
    </form>
  </div>
{% endblock content %}

core/templates/core/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">Online MarketPlace</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'items:itemsSearch' %}">Browse</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'items:new' %}">New Item</a>
          </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'conversation:inbox' %}">Inbox</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard:index' %}">Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout_user' %}">logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'signUp' %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user_login' %}">Login</a>
            </li>
          {% endif %}
          
        </ul>
        
      </div>
    </div>
  </nav>

core/templates/core/signup.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
<h1 class="text-center">Please Signup Here</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center">{{ 'Register Here' }}</div>
                <div class="card-body">
                    <form method="POST" action=".">
                        {% csrf_token %}
                
                        <div class="mb-3">
                            <label class="inline-block mb-2">Username</label><br>
                            {{ form.username }}
                        </div>
                
                        <div class="mb-3">
                            <label class="inline-block mb-2">Email</label><br>
                            {{ form.email }}
                        </div>
                
                        <div class="mb-3">
                            <label class="inline-block mb-2">Password</label><br>
                            {{ form.password1 }}
                        </div>
                
                        <div class="mb-3">
                            <label class="inline-block mb-2">Repeat password</label><br>
                            {{ form.password2 }}
                        </div>
                
                        {% if form.errors or form.non_field_errors %}
                            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                                {% for field in form %}
                                    {{ field.errors }}
                                {% endfor %}
                
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}
                
                        <button class="btn btn-primary btn-lg rounded-pill">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}